version: "3.9"
services:
  web:
    container_name: web
    build: 
      context: './WebApp/'
      dockerfile: Dockerfile

    ports:
      - 5000:5000
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - main-network

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network.
      - 1433:1433 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - ./mssql/sqlvolume:/var/opt/mssql
    networks:
      - main-network
  nginx:
    image: nginx:1.24.0
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - main-network
    
networks:
  main-network:
    driver: bridge
