version: "3.9"
services:
  web:
    build: 
      context: './WebApp/'
      dockerfile: Dockerfile

    # ports:
    #   - "5000:5000"
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - main-network
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - main-network
    
networks:
  main-network:
    driver: bridge
